### ISSUE TITLE
微博绑定用户名，密码太短。

### ISSUE THREAD

**Issue by vangogogo** [outman/birdbbs#4]
微博绑定用户名，密码太短。user里的默认密码“_PWD”长度没达到设置的最低值5.
另外绑定的页面只给出用户名的错误提示，其他错误没有提示，需要debug才能发现是什么原因没有绑定成功。建议加 <?php echo $form->errorSummary($user); ?>提示更加友好和全面。
![image](https://cloud.githubusercontent.com/assets/5194254/17472796/927b33b8-5d7f-11e6-97a5-3fab843aba70.png)

**Comment by outman** [comment]
@vangogogo 微博绑定用户只是存储了个默认密码，这个密码是不能用于登陆的。所以只是象征性的存储了个 _PWD 而已。一个不好的设计。

**Comment by vangogogo** [comment]
@outman  实际应用就是用户无法用微博帐号绑定，没有任何提示。debug以后发现是密码长度显示问题，把_PWD改成 _PWD_NONE就可以了。

**Comment by outman** [comment]
@vangogogo 这个我好像修复过，可能忘记提交上来了，有时间我看看。
